[package]
name = "vic3-defs"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Victoria 3 game definitions (goods, needs, PMs)"

[lints]
workspace = true

[dependencies]
jomini.workspace = true
postcard.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
proptest.workspace = true
