[package]
name = "vic3-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Victoria 3 analyzer CLI"

[lints]
workspace = true

[[bin]]
name = "vic3-cli"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
vic3-defs = { path = "../vic3-defs" }
vic3-goals = { path = "../vic3-goals" }
vic3-load = { path = "../vic3-load" }
vic3-prices = { path = "../vic3-prices" }
vic3-world = { path = "../vic3-world" }

[dev-dependencies]
assert_cmd = "2"
serde_json.workspace = true
